# Site
repository: L1thick/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Wagner
title: Support Specialist
email: RobertDWagner@iCloud.com
website: https://l1thick.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  L1thick
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: robert-w-067b811b4
# xing_username:
# pinterest_username:
youtube_username: /channel/UCnaVY7W6rN0kgV1RcFvo8uw
# googleplus_username:
# orcid_username:

# Additional icon links
additional_links:
# - title:
#   icon: (https://fontawesome.com/icons?d=gallery&m=free)
#   url:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hi, my name's Rob. I'm pretty good Systems Administrator with experiance with independantly managing 300+ Windows based work stations & laptops, 100+ <mark>iOS</mark> & <mark>Android</mark> devices, and 200+ <mark>VoIP</mark> and Cell Phones simultaneously. Most of my background is in manageing and deploying Windows based devices, however I've branch out into <mark>Apple Business Manager</mark> & <mark> Android for Work</mark> as part of the ever growing mobile work force. 
  
  When I'm not working with enterprise systems, I'm spening time working on my HomeLab which runs <mark>Linux Servers</mark> and <mark>Docker</mark> with <mark>Kubernetes</mark> for various web services I run. There have been a few itterations to my network that have seen differnet <mark>VPN</mark> servers, an occasional <mark>ESXi</mark> host, different Docker Nodes, a few different <mark>Raspberry Pi</mark> or <mark>Arduini</mark> setups.


  The primary technologies I use daily or are most proficient in include: Microsoft <mark>SCCM</mark> & related Deployment Tools, Cisco <mark>Meraki MDM</mark> w/ Apple Business Manager (<mark>ABM</mark>), Microsoft <mark>Windows 10</mark> & Apple <mark>macOS/ iOS</mark>, Ubiquity <mark>Unifi</mark> Network Manager & Hardware, VMware vSphere <mark>ESXi 6.7</mark> and other related VMWare Products (<mark>VEEAM B&R</mark>).

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My "Projects" and other HomeLab Endevors.
        link: github.com/L1thick
        # link_text: Project Website
        additional_links:
          - title:  Extr3mis microK8's Cluster
            icon: fab fa-github
            url: google.com
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I've learned to do it wrong enough ways to keep failing correctly. 
        description: | # this will include new lines to allow paragraphs
          Extremis is a 5 node Raspberry Pi Cluster that runs various Web Services. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The City of Steamboat Springs
        link: SteamboatSprings.net
        # link_text: steamboatsprings.net
        sub_title: Support Specialist
        caption: June 2016 - June 2021
        quote: >
          That DOS Program from the 90s is mission critial. Please, find a way to make it work.
        description: | # this will include new lines to allow paragraphs
            Government.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Southern New Hampshire University
        caption: 2020 - 2023
        sub_title: BS in Computer Science - Software Engineering
        description: | # this will include new lines to allow paragraphs
          Words words words

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - 
# Footer
footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
