# Site
repository:  L1thick/L1thick.github.io 
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Wagner
title: Support Specialist
email: RobertDWagner@iCloud.com
website: https://l1thick.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  L1thick
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: robert-w-067b811b4
# xing_username:
# pinterest_username:
# youtube_username:
# googleplus_username:
# orcid_username:

# Additional icon links
# https://fontawesome.com/icons?d=gallery&m=free
additional_links:
  - title: Youtube
  icon: fab fa-youtube
  url: https://www.youtube.com/channel/UCnaVY7W6rN0kgV1RcFvo8uw

# About Section
about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  Hey, my name’s Rob. I’m a pretty good Systems Administrator / Engineer and MCSA who has experience deploying: Windows, iOS, and Android devices. I also administer and manage them through their lifecycles with various remote tools from Meraki MDM or Microsoft SCCM. I’ve built the solutions from the ground up and kept constant updates and changes throughout. I also have the experience from my time in helpdesk and support ticket heavy aspects of the IT sphere. 
  
  When I’m not working with enterprise systems, I’m spending time working on my HomeLab. Here I’ve learned and deploy Docker for various service I’ll host; I’m a heavy PLEX user. I’ve begun to work with Kubernetes in a cluster project, and am always learning various programming languages to meet my goals. My homelab has also allowed me to keep my skills for the enterprise sharp, as I deploy many of the tools at home such as Veeam and vSphere. 

content:
  - title: Homelab Projects
    layout: list
    content:
      - layout: top-middle
        title:  Extr3mis microK8's Cluster
        quote: >
          I've learned to do it wrong enough ways to keep failing correctly. 
        description: | 
          Extremis is a 5 node Raspberry Pi Cluster that runs various Web Services through Docker. The master node is a Pi 4 4GB, while the nodes are the 3B+ boards. 
      - layout: top-middle
        title:  Ubiquity Unifi Network
        quote: >
          No one needs enterprise gear for their home; but it's cool. 
        description: | 
          It's the full hardware stack with a Raspberry Pi 3B+ running the controller software. A wireless mesh network was recently setup with two AP's. The network has a guest wifi, IoT wifi, and the VLAN configuration to secure the traffic with blocking on the firewall. Thanks to the Extremis Project, the network is also protected by a PiHole, has PiVPN, and other home automation services that require this gear to function properly.  
      - layout: top-middle
        title:  HomeBrewed HomeBridge HomeKit Server
        quote: >
          Is "Home" the new "i"? 
        description: | 
          It sounds as crazy as it is; have you ever noticed Apple's support for HomeKit is limited to a few vedors? Be a real shame if the community built something that allowed you to connected unsupported devices to HomeKit and use Apple's Cloud Encryption to automate your home. With this I was able to build an "IR-Blaster" from an ESP8600 to control a soundbar through Apple HomeKit buttons. I also force my Philips Hue to function through this server to allow additional ZigBee devices to speak to Apple HomeKit. 

  - title: Professional Experience 
    layout: list 
    content:
      - layout: left
        title: The City of Steamboat Springs
        link: SteamboatSprings.net
        # link_text: City Webpage
        sub_title: Support Specialist
        caption: June 2016 - June 2021
        quote: >
          That DOS Program from the 90s is mission critial. Please, find a way to make it work.
        description: |
            So, what I did:
            1. Supported Windows XP, 7, 8.x, & 10, macOS, iOS, and Android systems.
            2. Supported BYOD systems for end users and citizens.
            3. Built and managed PC images and application deployments with Windows SCCM and related technologies.
            4. VMWorkstation, ESXi, vSphere, and Hyper-V virtual environments for testing & production.
            5. Configured remote deployment & inventory management tools for Windows, iOS, & Android Devices through Microsoft SCCM, Software Center, O365, Cisco Meraki MDM, Android for Work, and Apple Business Manager.
            6. Kept documentation of Application Licenses. 
            7. Tested and evaluated new software & hardware for each departments various needs.
            8. Maintained WSUS & Microsoft Updates for Domain Workstations.
            9. Troubleshot and was Admin to the  VoIP Phone System on Cisco’s Unified Call Manager.
            10. Managed the technical administration and hardware for the Verizon Wireless Government Account. 
            11. Purchaser of new PCs, servers, peripheries, and other various equipment for our technical needs.
            12. Wrote training manuals and various documentation for internal IT staff and city staff.
            13. Built, supported, and maintained systems and equipment related to Steamboat TV6
            14. Scheduled, recorded and directed live T.V. broadcasts of City Council, Commission meetings, School Meetings, and other broadcast as needed.
            15. Provided	post-production editing	of audio & video files. 
            16. Built supported and maintained conference room systems for city employees and citizens. 
            17. Supported the CCTV systems at the facilities.
            18. Worked with ticketing system "Zendesk" & "Sysaid".

            Interesting Projects I've worked on:
            1. The original "Dueling Networks" solution for Police Car / Body camera off-load.
            2. The "Mission Critical Notchoes" Mobile Carrier Network Hotsport Solution.
            3. Swtiching CF-31's for iPad Pro's in our Ambulances & Fire Vehicles.
            4. The "Windows 10 Implimentation" & related Office 365 "COVID Responce Rollout".
            5. The Emulated DOS Records Database. No really, in 2017.

      - layout: left
        title: Computhink
        link: Computhink.com
        # link_text: Computhink
        sub_title: System Engineer
        caption: June 2014 - June 2016
        quote: >
            This application will OCR from the printer and it's intsalled with how many shoehorns? 
        description: |
            What did I do back then?
            1. Responsible for the continued maintenance and upgrades of all internal systems, servers, and misc. hardware.
            2. Built and	Maintained Lab	Environments	with:	Vista,	7,	8.x,	10,	Windows Server 2008, 2012, and various Linux Distros.
            3. Administrator to Salesforce, Desk.com, Azure Services, SQL Servers: 2008, 2012, 2014.
            4. Administrator to VMWare environments: ESXi 5.0 - 6.5, Workstation, VSphere and Veeam Backup & Replication.
            5. Administrator to and Supervision of Snapengage Support / Sales Chat Client.
            6. Administrator to VoIP phone systems on  RingCentral and 8x8.
            7. Technical Admin of Wordpress.org websites and cloud hosted services through Rackspace.
            8. Responsible for Domain Certificate compliance.
            9. Administrator of domain services: SMB, NFS, ADS, LDAP, DNS, Print Services, DHCP.
            10. Client software support and upgrades for Contenverse and related dependencies.
            11. Maintain and check for backups of all in house servers, and their redundancies.
            12. Maintain archival data of systems and user information as defined by policy.
            13. Rebuilt knowledge base and support forms for clients and internal IT & Sales staff.


  - title: Education & Certifications
    layout: list
    content:
      - layout: left
        title: Southern New Hampshire University
        caption: 2020 - 2023
        description: | 
          Working towards my BS in Computer Science with a focus on Software Engineering.
      - layout: left
        title: Microsoft Certified Solutions Associate, Windows 10 (MCSA)
        caption: Feb 2019
        description: | 
          Windows 10 is EoL in 2025, so thats cool!
      - layout: left
        title: Microsoft Certified Professional (MCP)
        caption: Oct 2018
        description: | 
          You get a cert, and you get a cert!
      - layout: left
        title: Trident International University
        caption: 2012 - 2013
        description: | 
          Studies towards a BS in Computer Science; incomplete. 
      - layout: left
        title: Moraine Valley Community College
        caption: 2009 - 2012
        description: | 
          1. Computer Support Associate Certification: Computer & LAN Technician
          2. Computer Support Associate Certification: Computer Technician   

# Footer
footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
