# Site
repository: L1thick/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Wagner
title: Support Specialist
email: RobertDWagner@iCloud.com
website: https://l1thick.github.io/

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  L1thick
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: robert-w-067b811b4
# xing_username:
# pinterest_username:
youtube_username: /channel/UCnaVY7W6rN0kgV1RcFvo8uw
# googleplus_username:
# orcid_username:

# Additional icon links
additional_links:
# - title:
#   icon: (https://fontawesome.com/icons?d=gallery&m=free)
#   url:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | 
  *Note: I'm currently working on this. I broke it recently and needed to start from scratch. Stand by - 7/5/21
  
  Hi, my name's Rob. I'm a pretty good Systems Administrator with experience with independently managing 300+ Windows based work stations & laptops, 100+ <mark>iOS</mark> & <mark>Android</mark> devices, and 200+ <mark>VoIP</mark> and Cell Phones simultaneously. Most of my background is in managing and deploying Windows based devices, however I've branch out into <mark>Apple Business Manager</mark> & <mark> Android for Work</mark> as part of the evergrowing mobile work force. 
  
  When I'm not working with enterprise systems, I'm spending time working on my HomeLab which runs <mark>Linux Servers</mark> and <mark>Docker</mark> with <mark>Kubernetes</mark> for various web services I run. There have been a few iterations to my network that have seen different <mark>VPN</mark> servers, an occasional <mark>ESXi</mark> host, different Docker Nodes, a few different <mark>Raspberry Pi</mark> or <mark>Arduino</mark> setups.

  The primary technologies I use daily or are most proficient in include: Microsoft <mark>SCCM</mark> & related Deployment Tools, Cisco <mark>Meraki MDM</mark> w/ Apple Business Manager (<mark>ABM</mark>), Microsoft <mark>Windows 10</mark> & Apple <mark>macOS/ iOS</mark>, Ubiquity <mark>Unifi</mark> Network Manager & Hardware, VMware vSphere <mark>ESXi 6.7</mark> and other related VMWare Products (<mark>VEEAM B&R</mark>).

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title:  Extr3mis microK8's Cluster
        quote: >
          I've learned to do it wrong enough ways to keep failing correctly. 
        description: | # this will include new lines to allow paragraphs
          Extremis is a 5 node Raspberry Pi Cluster that runs various Web Services through Docker. The master node is a Pi 4 4GB, while the nodes are the 3B+ boards. 

  - title: Experience 
    layout: list 
    content:
      - layout: left
        title: The City of Steamboat Springs
        link: SteamboatSprings.net
        # link_text: City Webpage
        sub_title: Support Specialist
        caption: June 2016 - June 2021
        quote: >
          That DOS Program from the 90s is mission critial. Please, find a way to make it work.
        description: |
            1. Supported Windows XP, 7, 8.x, & 10, macOS, iOS, and Android systems.
            2. Supported BYOD systems for end users and citizens.
            3. Built and managed PC images and application deployments with Windows SCCM, MDT, PXE, USMT, UDI, Software Center, and related technologies.
            4. VMWorkstation, ESXi, vSphere, and Hyper-V virtual environments.
            5. Configured remote deployment & inventory management tools for Windows iOS & Android Devices through Cisco Meraki MDM, Android for Work, and Apple Business Manager.
            6. Application License Retention & Documentation wizard. 
            Tested and evaluated new software & hardware for each departments various needs.
            Maintains WSUS & Microsft Updates for Domain Workstations.
            Troubleshoots and Administers VoIP Phone System on Cisco’s Unified Call Manager Solution.
            Managed the technical administration and hardware of the Verizon Wireless Government Account. 
            Purchase Administrator of new PCs, servers, peripheries, and various equipment.
            Wrote training manuals and various documentation for internal IT staff and city staff.
            Built, supported, and maintained systems and equipment related to Steamboat TV6, setting up program schedules, and recording and directing live T.V. broadcasts of City Council, Commission meetings, School Meetings, and other broadcast as needed.
            Provided	post-production editing	of audio & video files. 
            Built supported and maintained conference room systems for city employees and citizens. 
            Supported City’s CCTV systems.

            Some "Nicknamed" projects I've worked:
            1. "Dueling Networks" solution for Police Car / Body camera off-load.
            2. The "Mission Critical Notchoes" Mobile Carrier Network Hotsport Solution.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Southern New Hampshire University
        caption: 2020 - 2023
        sub_title: BS in Computer Science - Software Engineering
        description: | # this will include new lines to allow paragraphs
          Words words words

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - 
# Footer
footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
