# Site
repository: L1thick/resume
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Robert Wagner
title: Suport Specialist
email: RobertDWagner@iCloud.com
website: www.github.com/L1thick/resume

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: 
github_username:  L1thick
# stackoverflow_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
linkedin_username: robert-w-067b811b4
# xing_username:
# pinterest_username:
youtube_username: UCnaVY7W6rN0kgV1RcFvo8uw
# googleplus_username:
# orcid_username:

# Additional icon links
additional_links:
- title: Google.com
  icon: fas fa-globe
  url: https://www.google.com
# - title:
#   icon: (https://fontawesome.com/icons?d=gallery&m=free)
#   url:

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Rob

  I am most skilled with: Microsoft <mark>SCCM</mark> & related Deployment Tools, Cisco <mark>Meraki MDM</mark> w/ Apple Business Manager (<mark>ABM</mark>), Microsoft <mark>Windows 10</mark> & Apple <mark>macOS/ iOS</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: My "Projects" and other HomeLab Endevors.
        link: github.com/L1thick
        # link_text: Project Website
        additional_links:
          - title:  Extr3mis microK8's Cluster
            icon: fab fa-github
            url: google.com
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          I've learned to do it wrong enough ways to keep failing correctly. 
        description: | # this will include new lines to allow paragraphs
          Extremis is a 5 node Raspberry Pi Cluster that runs various Web Services. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The City of Steamboat Springs
        link: SteamboatSprings.net
        # link_text: steamboatsprings.net
        sub_title: Support Specialist
        caption: June 2016 - June 2021
        quote: >
          That DOS Program from the 90s is mission critial. Please, find a way to make it work.
        description: | # this will include new lines to allow paragraphs
            Government.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Southern New Hampshire University
        caption: 2020 - 2023
        sub_title: BS in Computer Science - Software Engineering
        description: | # this will include new lines to allow paragraphs
          Words words words

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - 
# Footer
footer_show_references: true
# references_title: References on request

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
